// Sentry — browser-side init. This is the canonical client config under
// the Next 15 + Sentry pattern (supersedes the old sentry.client.config.ts).
// Generated by the Sentry wizard, then tuned for a single-owner OS on the
// free tier.
import * as Sentry from "@sentry/nextjs";

// Client DSNs are public by design (they ship in the browser bundle), so a
// literal fallback is fine — but prefer the env var so prod/preview can
// differ without a code change.
const dsn =
  process.env.NEXT_PUBLIC_SENTRY_DSN ??
  "https://64f3bec42556d4ea32db393df96be969@o4511458593669120.ingest.us.sentry.io/4511458596552704";

Sentry.init({
  dsn,

  // 10% perf tracing — plenty for one user, keeps you well under the free
  // tier's transaction quota.
  tracesSampleRate: 0.1,

  // Session replay quota on the free tier is tight (50/mo). Don't record
  // normal sessions; DO record a replay when an error fires — that's the
  // useful case ("what did I click right before it broke").
  replaysSessionSampleRate: 0,
  replaysOnErrorSampleRate: 1.0,
  integrations: [Sentry.replayIntegration()],

  enableLogs: true,

  // Single-owner OS — no value capturing your own IP, and staying PII-clean
  // keeps the door open to shipping to others later. (Matches server config.)
  sendDefaultPii: false,

  environment: process.env.NEXT_PUBLIC_VERCEL_ENV ?? "development",

  // Drop noise that isn't actionable
  ignoreErrors: [
    "NotAllowedError",     // user cancelled a passkey / biometric prompt
    "AbortError",          // navigated away mid-fetch
    "Non-Error promise rejection captured",
  ],
});

export const onRouterTransitionStart = Sentry.captureRouterTransitionStart;
